name: Publish

on:
  release:
    types:
      - published

concurrency:
  group: publish
  cancel-in-progress: false

permissions: {}

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for OIDC
      pull-requests: write # for labelling PRs
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.release.tag_name }}
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          package-manager-cache: false # no cache poisoning please
          check-latest: true

      - run: npm ci
      - run: npm run build

      - name: Trusted Publish with Provenance
        run: |
          npm publish
        working-directory: dist/ngx-toastr

      - name: Update Release PR Label
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            // Find the PR.
            const { owner, repo } = context.repo;
            const commit_sha = context.payload.release.target_commitish;
            const { data: pullRequests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner,
              repo,
              commit_sha,
            });
            if (pullRequests.length === 0) {
              core.info(`No pull request found for '${commit_sha}'.`);
              return;
            }
            const releasePullRequests = pullRequests.filter(pullRequest =>
              pullRequest.merged_at &&
              pullRequest.base.ref === context.payload.repository.default_branch &&
              pullRequest.head.ref.startsWith('release-please--branches--')
            );
            if (releasePullRequests.length !== 1) {
              throw new Error(`Expected one release pull request for '${commit_sha}', found ${releasePullRequests.length}.`);
            }

            // Swap labels.
            const issue_number = releasePullRequests[0].number;
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: ['autorelease: published'],
            });
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number,
              name: 'autorelease: tagged',
            });

            // Comment on PR.
            const releaseTag = context.payload.release.tag_name;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `🚀 Release \`${releaseTag}\` has been published!`,
            });
